--CREATE TABLE `person` (
--  `id` bigint NOT NULL AUTO_INCREMENT,
--  `endereco` varchar(100) NOT NULL,
--  `primeiro_nome` varchar(80) NOT NULL,
--  `Sexo` varchar(6) NOT NULL,
--  `ultimp_nome` varchar(80) NOT NULL,
--  PRIMARY KEY (`id`)
--) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COMMENT='Tabela para teste de conexão e persitencias de API Rest Full';
